-- ── Snowflake Setup Script ─────────────────────────────────────────────────
-- Run as ACCOUNTADMIN
-- Creates warehouse, databases, schemas, roles, and users

-- Warehouse
CREATE WAREHOUSE ANALYTICS_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Main compute warehouse — auto-suspends after 60s to save credits';

-- Databases
CREATE DATABASE BRONZE_DB;
CREATE DATABASE SILVER_DB;
CREATE DATABASE GOLD_DB;

-- Schemas
CREATE SCHEMA BRONZE_DB.TAXI;
CREATE SCHEMA BRONZE_DB.WEATHER;
CREATE SCHEMA BRONZE_DB.ZONES;
CREATE SCHEMA BRONZE_DB.COMPLAINTS;
CREATE SCHEMA BRONZE_DB.CLICKSTREAM;
CREATE SCHEMA SILVER_DB.TAXI;
CREATE SCHEMA SILVER_DB.WEATHER;
CREATE SCHEMA SILVER_DB.COMPLAINTS;
CREATE SCHEMA SILVER_DB.CLICKSTREAM;
CREATE SCHEMA GOLD_DB.MARTS;
CREATE SCHEMA GOLD_DB.LIVE;

-- Roles
CREATE ROLE PIPELINE_ROLE
  COMMENT = 'Used by Databricks pipelines — full read/write on all layers';

CREATE ROLE REPORTING_ROLE
  COMMENT = 'Used by Superset dashboard — read only on Gold marts';

-- Warehouse grants
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE PIPELINE_ROLE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE REPORTING_ROLE;

-- Pipeline role permissions
GRANT ALL PRIVILEGES ON DATABASE BRONZE_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON DATABASE SILVER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON DATABASE GOLD_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE BRONZE_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SILVER_DB TO ROLE PIPELINE_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE GOLD_DB TO ROLE PIPELINE_ROLE;

-- Reporting role permissions
GRANT USAGE ON DATABASE GOLD_DB TO ROLE REPORTING_ROLE;
GRANT USAGE ON SCHEMA GOLD_DB.MARTS TO ROLE REPORTING_ROLE;
GRANT USAGE ON SCHEMA GOLD_DB.LIVE TO ROLE REPORTING_ROLE;

-- Users
CREATE USER PIPELINE_USER
  PASSWORD = 'PipelineUser@2024'
  DEFAULT_ROLE = PIPELINE_ROLE
  DEFAULT_WAREHOUSE = ANALYTICS_WH
  COMMENT = 'Service user for Databricks pipeline';

CREATE USER REPORTING_USER
  PASSWORD = 'ReportingUser@2024'
  DEFAULT_ROLE = REPORTING_ROLE
  DEFAULT_WAREHOUSE = ANALYTICS_WH
  COMMENT = 'Service user for Superset dashboard';

-- Role assignments
GRANT ROLE PIPELINE_ROLE TO USER PIPELINE_USER;
GRANT ROLE REPORTING_ROLE TO USER REPORTING_USER;
GRANT ROLE PIPELINE_ROLE TO ROLE ACCOUNTADMIN;
GRANT ROLE REPORTING_ROLE TO ROLE ACCOUNTADMIN;